---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: locat
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Import Vpc setup
      include_vars: vars/vpc_setup

    - name: Import vprofile setup variable
      include_vars: vars/vprostacksetup

    - name: Create vprofile EC2 key
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out

    - name: Save private key into file
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed


